spring:
  application:
    name: Resume-AI-Analyzer

  datasource:
    url: jdbc:postgresql://localhost:5432/resume-ai
    username: postgres
    password: vinolancy
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true

server:
  port: 8000